module.exports = {
  validUsername: "Test1234!",
  validPassword: "Test1234!",
  invalidUsername: "utttt$$",
  invalidPassword: "!!!!!!!!!",
  validUsername1: "32!",
  validPassword1: "Test1234!",
  validAuthor: "Richard",
  validTitle: "Learning JavaScript Design Patterns",
  validPublisher: "No Starch Press",
  invalidSearchString1: "",
  invalidSearchString2: "*",
  collectionFullUser: "CollectionFull",
  collectionFullPassword: "CollectionFull1!",
};
